### ISSUE TITLE
Only working with devMode enabled in Craft 2.9.1

### ISSUE THREAD

**Issue by siebird** [TopShelfCraft/Printmaker#2]
On client's live site the PDF generation throws an error or it's empty. Enabling `devMode => true` generates a working PDF. Very odd.

Using Printmaker 1.3.2

**Comment by ohlincik** [comment]
Recently upgraded both Craft to v2.9.2 and Printmaker to v1.3.2 and we're experiencing the same issue. The PDF contents are not streamed from the server unless `devMode => true`.

I'd rather not have the dev mode enabled on a live server. Any idea what's happening here and when a fix may be available?

**Comment by siebird** [comment]
I haven't tested this on the live server as we ended up upgrading to Craft 3.

However, the issue is with how DomPDF dumps/generates the PDF with the `exit();` command which Craft thinks is an error and blocks it. Try adding `ob_end_clean();` to [line 268](https://github.com/TopShelfCraft/Printmaker/blob/1c7429d1a7b71cd1ab758c2b39cb5d2375ec249d/printmaker/models/Printmaker_PdfModel.php#L268)

**Comment by michaelrog** [comment]
🤔  will look there for starters — thanks, Austin!

**Comment by ohlincik** [comment]
@siebird, I just tested your suggestion and indeed it works! Thanks for taking the time to post your comment here. Much appreciated!

@michaelrog I'm just gonna monkey-patch the plugin on my end for the time being, until you had time to look further into it and perhaps push a new version of the plugin out. Let me know if there is any way I can help.

**Comment by michaelrog** [comment]
@ohlincik This fix is included in [1.4.0](https://github.com/TopShelfCraft/Printmaker/releases/tag/1.4.0).

**Comment by ohlincik** [comment]
Thanks, @michaelrog!
